Matterbot:
  host: "<your-mattermost-host>"
  port: 443
  scheme: "https"
  username: "<mattermost bot account name>"
  password: "<mattermost bot password>"
  teamname: "<mattermost team identifier>"
  logfile: "matterfeed.log"
  msglength: 16383 # For old Mattermost versions (<=5.x), use msglength: 4000!

Modules:
  moduledir: "modules"
  commanddir: "commands"
  window: 20
  timer: 600

debug: False
